### ISSUE TITLE
🚀 - Moonlight Theme

### ISSUE THREAD

**Issue by riccardoperra** [riccardoperra/codeimage#20]
This task consist of creating a new theme for CodeImage editor using CodeMirror API.

https://github.com/atomiks/moonlight-vscode-theme

---

## Instructions for contributions
- Follow the [CONTRIBUTING.md](https://github.com/riccardoperra/codeimage/blob/main/CONTRIBUTING.md) instructions to prepare your environment. 
> **NOTE** If your intention is to only develop a new theme, you don't need to use docker or install everything. You will work only on [@codeimage/highlight](https://github.com/riccardoperra/codeimage/tree/main/packages/highlight) package
- Move to [packages/highlight](https://github.com/riccardoperra/codeimage/tree/main/packages/highlight). You will see a [How to create a new theme section](https://github.com/riccardoperra/codeimage/tree/main/packages/highlight) in the README.md file .
- Run the `pnpm generate:theme` script and put the `moonlight` theme name
- Open the theme playground with pnpm dev (from the highlight package) or pnpm dev --filter=@codeimage/highlight (from the root folder)

For further help you can ask for help in the comments below

**Comment by SIMRAN88** [comment]
Can I please work on this?

**Comment by riccardoperra** [comment]
Yes 😁 I Will check your other pr asap

**Comment by riccardoperra** [comment]
closed by #372
