### ISSUE TITLE
🚀 - Monokai Pro Theme

### ISSUE THREAD

**Issue by riccardoperra** [riccardoperra/codeimage#21]
Color scheme https://monokai.pro/

This task consist of creating a new theme for CodeImage editor using CodeMirror API.

---

## Instructions for contributions
- Follow the [CONTRIBUTING.md](https://github.com/riccardoperra/codeimage/blob/main/CONTRIBUTING.md) instructions to prepare your environment. 
> **NOTE** If your intention is to only develop a new theme, you don't need to use docker or install everything. You will work only on [@codeimage/highlight](https://github.com/riccardoperra/codeimage/tree/main/packages/highlight) package
- Move to [packages/highlight](https://github.com/riccardoperra/codeimage/tree/main/packages/highlight). You will see a [How to create a new theme section](https://github.com/riccardoperra/codeimage/tree/main/packages/highlight) in the README.md file .
- Run the `pnpm generate:theme` script and put the `monokaiPro` theme name
- Open the theme playground with pnpm dev (from the highlight package) or pnpm dev --filter=@codeimage/highlight (from the root folder)

For further help you can ask for help in the comments below

**Comment by SIMRAN88** [comment]
Please assign this to me

**Comment by SIMRAN88** [comment]
Please assign this to me

**Comment by riccardoperra** [comment]
Done
