### ISSUE TITLE
🚀 - Window Message API/VSCode Extension

### ISSUE THREAD

**Issue by Kyza** [riccardoperra/codeimage#216]
### Which @codeimage/* package(s) are relevant/releated to the feature request?

codeimage

### Description

I am making an open source VSCode extension that embeds CodeImage in an iframe for people to use quickly and syncs data from the VSCode editor to the CodeImage editor.

Since it's running in an iframe I don't have enough access to the page to be able to do syncing with things such as the file name or user's selection in the editor.

I would really appreciate it if you would add an API using the Window Message API (`window.postMessage` and `window.addEventListener`) so that important state can be controlled from the parent frame. Or if you would like control over it I would give you the code for the extension.

**Comment by riccardoperra** [comment]
This is definitely useful for external integrations 😄

If I understand correctly, you have to listen specific events and receive/send data, right?

For example:

- VSCode send a "SaveImage" type event -> CodeImage save and returns back the image file

- VSCode send "SetOptions" event -> CodeImage update the options

If yes, which type of events do you need to handle in your VS Code extensions? I would like to understand the flow to have more context
