### ISSUE TITLE
🚀 - Shadow editing

### ISSUE THREAD

**Issue by riccardoperra** [riccardoperra/codeimage#239]
Currently the default shadow is the `lg` variant from vanilla-extract
https://github.com/riccardoperra/codeimage/blob/8c5135861293c37d7236c5aa73e3d89eab1b877b/apps/codeimage/src/state/terminal.ts#L28-L34

Users may want to select from a set of shadows to style the Terminal. The new control should be in the `Window` group.
### Ideas
- Listbox with values like `normal`, `none`, `large` etc.
- Like color picker, using a dropdown with shadow picker from presets

> ** Note **
Example of beautiful shadows https://getcssscan.com/css-box-shadow-examples

**Comment by hackpirodev** [comment]
@riccardoperra are you working on this issue? In case you not started yet can you assign me?

**Comment by riccardoperra** [comment]
@hackpirodev done 😁
