### ISSUE TITLE
🚀 - OAuth authentication

### ISSUE THREAD

**Issue by riccardoperra** [riccardoperra/codeimage#240]

**Comment by hackpirodev** [comment]
@riccardoperra the auth now it's implemented using Auth0,  we won't change it, right?

**Comment by riccardoperra** [comment]
> @riccardoperra the auth now it's implemented using Auth0, we won't change it, right?

Yes, exactly. Cannot close that issue until it is merged to Main

**Comment by riccardoperra** [comment]
merged with #325  in main
