### ISSUE TITLE
🚀 - Add support for multiple tabs

### ISSUE THREAD

**Issue by micnic** [riccardoperra/codeimage#257]
### Which @codeimage/* package(s) are relevant/releated to the feature request?

codeimage

### Description

As the title says, it would be nice to have multiple tabs, be able to switch between them and maybe be able to generate multiple images.

**Comment by riccardoperra** [comment]
Hi @micnic, thanks for your proposal!

Just to let me understand correctly, your idea is to handle multiple workspaces with his own configuration? I've made a quick mockup as example

![codeimage dev__p=JTdCJTIydGVybWluYWwlMjIlM0ElN0IlMjJzaG93SGVhZGVyJTIyJTNBdHJ1ZSUyQyUyMnR5cGUlMjIlM0ElMjJtYWNPcyUyMiUyQyUyMnRhYk5hbWUlMjIlM0ElMjJpbmRleC5zcGVjLnRzJTIyJTJDJTIyYWNjZW50VmlzaWJsZSUy (3)](https://user-images.githubusercontent.com/37072694/169655296-26ac636d-519a-4731-bfe5-b9a7aa2b8e83.png)

**Comment by micnic** [comment]
Here is a representation of what I have in mind:

![image](https://user-images.githubusercontent.com/1449826/169657979-c51e2828-b3fc-4164-aa92-3558782c128d.png)

In this way it's possible to display a little project and have a context of what files are available and what is the link between them. Tabs would be clickable and have their own code content.

Generating multiple images would be an optional feature, maybe to export them as an .zip archive, but generating for the current active tab is totally fine in my humble opinion.

**Comment by riccardoperra** [comment]
Ok 👍 

This could be the style when the "tab accent" is disabled, what do you think?
![0d508f16-5a67-4180-8582-94db5c525678](https://user-images.githubusercontent.com/37072694/169658708-b2793552-3a64-451f-8bff-6a575da39860.png)

A possible issue could be handle the style when there is no much space left

**Comment by micnic** [comment]
I like this design for disabled "tab accent", would just remove the background of the + (new tab) button

> One of the possible issue with this could be handling the style when there is no much space left. Do you think it is better to manage it with overflow-scroll or with an "Other" tab (maybe with the ellipsis-h icon) which show dinamically?

I am a fan of firefox's solution with tabs that do not fit in the width, but it would be a bit more work to implement and might be not that adequate for the minimalistic design of codeimage.

**Comment by riccardoperra** [comment]
Hi @micnic, I just wanted to inform you that your issue is currently in progress.

There are several things to fix, like some missing data synchronization reloading the page,  themissing theme switcher header and the style of tab accent which is currently in progress


https://codeimage-dhywm38yd-riccardoperra.vercel.app/

**Comment by micnic** [comment]
In my opinion theming or other visual customization should not be set for each tab independently. What I was expected is that only the content of the tab changes when I switch to another tab, visuals should remain the same.

The solution that you implemented for overflowing tabs seems pretty good (similar to chrome behavior), nice job.

While testing the current version another feature idea came into my mind: to implement the possibility to move the tabs by dragging them around.

Either way I like the current progress on this feature. Will follow the changes you are doing in the feature branch, I'm a react dev, just recently discovered solid and I really like it, will check and see if I can give any advice about implementation details.

**Comment by riccardoperra** [comment]
> In my opinion theming or other visual customization should not be set for each tab independently. What I was expected is that only the content of the tab changes when I switch to another tab, visuals should remain the same.

You’re right, this doesn’t make so much sense right now. I handled them separately in the case I need it for future integrations, but handling a global shared state instead of forwarding all theme options changes through all tabs is much easier to maintain. I’ll refactor the state later 😄

> While testing the current version another feature idea came into my mind: to implement the possibility to move the tabs by dragging them around.

I thought the same thing. Hoping that I don’t have to refactor again the tabs styles, I’ll try [solid-dnd](https://solid-dnd.com/) which could fit in this case

Thanks for your feedback and your time!

**Comment by riccardoperra** [comment]
Hi @micnic, the https://github.com/riccardoperra/codeimage/pull/265 is almost done.

I'm planning to clean-up the code and release it in a few days. Any feedback is welcome 😄

Demo (you probably need to Ctrl+Shift+R to get the latest version)
https://codeimage-git-257-add-support-for-multiple-tabs-riccardoperra.vercel.app/

Here's a small changelog compared to a few days ago:
- Styling options are now shared. Only the language will be custom for each tab and automatically change also in base of the extension used on the tab name
- Add drag and drop. The y-axis is locked and it has boundary parent (you can only move it inside the container wrapper)
- Tabs are limited to a max of 6
- Close icon will not show up if there is not enough space
- Multi-tabs is available for windows terminal theme
- Theme switcher will now show an example code with highlighing

**Comment by micnic** [comment]
Looks great! The functionality and UI are really good.

Just observed the "New Tab" button icon is not centered, would be nice to have it in the middle of the button:
<img width="650" alt="image" src="https://user-images.githubusercontent.com/1449826/171993778-5ab80b74-1d0f-406d-8af4-00691b94f005.png">

Also some dark themes (including the one in the upper screenshot) have low contrast between active and inactive tabs which makes a little difficult to understand what tab is being edited. Is it possible to improve tab colors?

**Comment by riccardoperra** [comment]
> Also some dark themes (including the one in the upper screenshot) have low contrast between active and inactive tabs which makes a little difficult to understand what tab is being edited. Is it possible to improve tab colors?

Thank you for this feedback! Anyway, I probably will have to recalibrate my monitor 😄 
I've opened this #271 with a preview https://codeimage-git-fixeditortabcolors-riccardoperra.vercel.app/

Here's the theme that I've fixed:
- NightOwl
- Material Ocean
- Synthwave'84
- Material Volcano
- One Light 
- Coldark Cold
- MaterialLight

**Comment by micnic** [comment]
I think I found a small bug, steps to reproduce:
1. Open a new "Untitled" tab
2. Close the old tab

Observed:
The editor window shrinks and only if you try to edit the tab name the content of the tab appears back.

![image](https://user-images.githubusercontent.com/1449826/172072310-e48b6fdc-0aab-42c0-a021-a58f0090782d.png)

**Comment by riccardoperra** [comment]
Oh yes, I was trying to fix a render issue while removing the current active tab and I had forgotten to set there the right fallback 😄 https://github.com/riccardoperra/codeimage/pull/271/commits/7d118e0f719072f36d35866a5006da6096206fbc#diff-8eb4581d578ae507dae5bd6e6e9edaa5421632b1fe29929207d6a7a23a0fc839R104-R108

Thanks again

**Comment by micnic** [comment]
From my side it's ready to be merged, LGTM!

**Comment by riccardoperra** [comment]
Released 😄
