### ISSUE TITLE
🐞 - Exported image should not have the active background if there is only one tab

### ISSUE THREAD

**Issue by riccardoperra** [riccardoperra/codeimage#278]
### Which @codeimage/* package(s) are the source of the bug?

codeimage

### Description

![image](https://user-images.githubusercontent.com/37072694/173011066-3fb6dc71-0bbc-45ee-8d31-af84499d5e91.png)

## Expected export

![image](https://user-images.githubusercontent.com/37072694/173012458-bf0e62e5-12a4-4f74-97fe-61330e3c5130.png)

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by piyushjohnson** [comment]
Started exploring this issue, anyone working on this one

**Comment by riccardoperra** [comment]
Hi @piyushjohnson, I think no. I can assign this issue to you 😄

If you need any information or support, feel free to ask!

Just a small recommandation

**Comment by riccardoperra** [comment]
Hi @piyushjohnson, I think no. I can assign this issue to you 😄

If you need any information or support, feel free to ask!

Just a small recommandation: currently the `export` function clone each node and exports everything is present in the DOM. The simplest way to resolve this issue is to remove the `active` style of the tab if there is only one tab present.

https://github.com/riccardoperra/codeimage/tree/main/apps/codeimage/src/components/Terminal/Tabs
