### ISSUE TITLE
Add Poimandres Theme

### ISSUE THREAD

**Issue by Kalmarv** [riccardoperra/codeimage#301]
### Which @codeimage/* package(s) are relevant/releated to the feature request?

highlight

### Description

Hi, just wondering if you’re open to PRs for new themes.

I’d like to add the [Poimandres](https://github.com/drcmda/poimandres-theme) theme if so.

**Comment by riccardoperra** [comment]
Hi Kalmarv, yes these prs are fine 😄

The README is not complete so I am writing you some information here to build it, and if you need any help, write me.

- The `createPrismJsTheme` doesn't exist anymore, you should use the newest `createTheme` function which provides a theme for the editor including autocomplete, dropdown, box preview etc. Here you can find the latest added theme with an example https://github.com/riccardoperra/codeimage/blob/main/packages/highlight/src/lib/themes/githubDark/index.ts

- Each theme must be in his own folder and must exports two files: index.ts and <theme>.ts
- To compile the theme you should add in the array the folder name you used https://github.com/riccardoperra/codeimage/blob/6e3dd296ee1e6f61fb93bfcdb5f6c5233749fb16/packages/highlight/rollup.config.ts#L9
- Remember to add the module and type definition in package.json https://github.com/riccardoperra/codeimage/blob/6e3dd296ee1e6f61fb93bfcdb5f6c5233749fb16/packages/highlight/package.json#L119

if you need to test it in the application, you should import dynamically the theme in the registry

https://github.com/riccardoperra/codeimage/blob/main/apps/codeimage/src/state/theme/themeRegistry.ts (order of this array matter, i think I would put it under the synthwave84 theme)
