### ISSUE TITLE
🚀 - Add Vitesse theme

### ISSUE THREAD

**Issue by riccardoperra** [riccardoperra/codeimage#305]
### Which @codeimage/* package(s) are relevant/releated to the feature request?

highlight

### Description

This task consist of creating a new theme for CodeImage editor using CodeMirror API.

https://github.com/antfu/vscode-theme-vitesse

---

## Instructions for contributions
- Follow the [CONTRIBUTING.md](https://github.com/riccardoperra/codeimage/blob/main/CONTRIBUTING.md) instructions to prepare your environment. 
> **NOTE** If your intention is to only develop a new theme, you don't need to use docker or install everything. You will work only on [@codeimage/highlight](https://github.com/riccardoperra/codeimage/tree/main/packages/highlight) package
- Move to [packages/highlight](https://github.com/riccardoperra/codeimage/tree/main/packages/highlight). You will see a [How to create a new theme section](https://github.com/riccardoperra/codeimage/tree/main/packages/highlight) in the README.md file .
- Run the `pnpm generate:theme` script and put the `vitesse` theme name
- Open the theme playground with pnpm dev (from the highlight package) or pnpm dev --filter=@codeimage/highlight (from the root folder)

For further help you can ask for help in the comments below

**Comment by Vikki123** [comment]
@riccardoperra  Could you assign this to me ?

**Comment by Vikki123** [comment]
Also which theme are we looking for ? Is it Vitesse light or dark ?

**Comment by Vikki123** [comment]
Sure .. i created a PR for dark theme. Please check it out.

**Comment by riccardoperra** [comment]
merged #378
