### ISSUE TITLE
🐞 - Not able to download code image

### ISSUE THREAD

**Issue by hadiyarajesh** [riccardoperra/codeimage#308]
### Which @codeimage/* package(s) are the source of the bug?

codeimage

### Description

I'm not able to download code snippet as image. Following error appear in browser console. I'm not sure if it's helpful or not.
```
App.28e94405.js:8     
    Uncaught ReferenceError: umami is not defined
    at HTMLButtonElement.g [as $$click] (App.28e94405.js:8:18532)
    at HTMLDocument.ua (index.ce6602ba.js:1:21652)
```

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by riccardoperra** [comment]
Hi @hadiyarajesh, unfortunately I'm not able to reproduce that issue.

I need some information:
- Are you using CodeImage 0.21.1? You can view the current version of the app in the right bottom space of the Canvas
- Did you tried to reset cache / disable network cache from network? It seems that the service which I use to track some analytics is not loading correctly, but it should.
![image](https://user-images.githubusercontent.com/37072694/179912387-c816372b-25ed-47aa-863a-a5803d4fa62c.png)
- Are you using latest version of Chrome? If not, which one? Mine is v104

Thank you for reporting, I'll try to fix it anyway

**Comment by hadiyarajesh** [comment]
HI @riccardoperra ,

Yes, I was using ad blocker [uBlock origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm) on microsoft edge and disabling it resolved the issue.

With adblocker enabled, I was getting ` Uncaught ReferenceError: umami is not defined` error as mentioned in previous response.

Thank you for suggesting solution.

**Comment by riccardoperra** [comment]
Good to know that! I didn't know these extensions could block also umami, so I'll deploy a fix in some hours that will prevent you from throwing that error anyway. Thank you
