### ISSUE TITLE
🐞 - changing the shadow does not work and causes error

### ISSUE THREAD

**Issue by apollo79** [riccardoperra/codeimage#311]
### Which @codeimage/* package(s) are the source of the bug?

Don't known / other

### Please provide a screenshot or a video to a minimal reproduction of the bug

![Screenshot 2022-07-22 184124](https://user-images.githubusercontent.com/90517340/180485465-049b02d8-42bc-450c-a068-e0ab9a9f359e.png)

### Description

If I try to select a different shadow than "Bottom", nothing visible happens, and the error "umami is not defined" appears in the console of the browser.

### Which browsers have you used?

- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by riccardoperra** [comment]
Hi @apollo79 , do you have any adblocker? 

This seems that same issue https://github.com/riccardoperra/codeimage/issues/308

**Comment by riccardoperra** [comment]
I've just deployed right now a new version with the newest umami script src and host. You can now inject that script even using AdBlockers like `uBlock origin`. 

![image](https://user-images.githubusercontent.com/37072694/180492230-cd91ff9b-ab26-48cd-ab55-1641f3cf1b45.png).

Anyway now adBlockers will block `/api/collect` which now prevents me from understanding how much a certain feature is used.

If I have to pay attention even to external code every time I go crazy
