### ISSUE TITLE
Loading indicator when exporting as image🚀 - 

### ISSUE THREAD

**Issue by hadiyarajesh** [riccardoperra/codeimage#330]
### Description

Currently, there is no visual indicator when exporting image as png/jpeg like that. 
It would be good if we add circular or similar loading indicator when exporting as image to let user know about the loading process.

**Comment by riccardoperra** [comment]
Hey @hadiyarajesh , currently the present indicator is that.

![image](https://user-images.githubusercontent.com/37072694/185762759-257dae1e-17d5-4281-a703-f03a0f81ef55.png)

We may replace the Export default icon with the Loading indicator icon while loading, what do you think? The export process is actually very fast and should never take more than 300/400ms I think

**Comment by hadiyarajesh** [comment]
Yes, that should be a good option. We can have a loading indicator instead of default icon.
Yes it's very fast, but what if somehow my browser is slow and taking time? In such (and all) cases, loading indicator provides a better visuals IMO. We can have a simple circular loading in export button or beside it .

**Comment by riccardoperra** [comment]
Hey @hadiyarajesh, I've opened a PR with the preview 😄 
https://codeimage-git-330-loading-indicator-when-e-7463b2-riccardoperra.vercel.app/

If everything is ok I'll make a deploy in a few hours.

Thanks :)

**Comment by hadiyarajesh** [comment]
Tried it and looks perfect. Thanks for quick resolution. 🥳

**Comment by riccardoperra** [comment]
Released 📦 [v0.21.3](https://github.com/riccardoperra/codeimage/releases/tag/v0.21.3)

I've also add support for XML and Json with their own highlighting and icons 😄
