### ISSUE TITLE
🚀 - Add Panda theme

### ISSUE THREAD

**Issue by riccardoperra** [riccardoperra/codeimage#366]
### Which @codeimage/* package(s) are relevant/releated to the feature request?

highlight

### Description

This task consist of creating a new theme for CodeImage editor using CodeMirror API.

https://github.com/tinkertrain/panda-syntax-vscode

---

## Instructions for contributions
- Follow the [CONTRIBUTING.md](https://github.com/riccardoperra/codeimage/blob/main/CONTRIBUTING.md) instructions to prepare your environment. 
> **NOTE** If your intention is to only develop a new theme, you don't need to use docker or install everything. You will work only on [@codeimage/highlight](https://github.com/riccardoperra/codeimage/tree/main/packages/highlight) package
- Move to [packages/highlight](https://github.com/riccardoperra/codeimage/tree/main/packages/highlight). You will see a [How to create a new theme section](https://github.com/riccardoperra/codeimage/tree/main/packages/highlight) in the README.md file .
- Run the `pnpm generate:theme` script and put the `panda` theme name
- Open the theme playground with pnpm dev (from the highlight package) or pnpm dev --filter=@codeimage/highlight (from the root folder)

For further help you can ask for help in the comments below

**Comment by riccardoperra** [comment]
Hey @TGlide , yes and thank you 😊 

feel free to ask for any help. If you have issues starting the dev server, check this issue too 

https://github.com/riccardoperra/codeimage/issues/365#issuecomment-1269872447

**Comment by TGlide** [comment]
Hey @riccardoperra ! I've just submitted the PR, though I ran into an issue. I was unable to correctly theme some properties, as there were no available options defined in `StyledHighlightOptions` for them. e.g. I couldn't stylize the `return` keyword independently.
