### ISSUE TITLE
🚀 - Fleet Dark Theme

### ISSUE THREAD

**Issue by riccardoperra** [riccardoperra/codeimage#380]
### Which @codeimage/* package(s) are relevant/releated to the feature request?

highlight

### Description

Add fleet dark theme

**Comment by SIMRAN88** [comment]
Please assign this to me

**Comment by SIMRAN88** [comment]
Hey @riccardoperra I have updated , please have a look

**Comment by riccardoperra** [comment]
> Hey @riccardoperra I have updated , please have a look

There are no changes in the pr

**Comment by SIMRAN88** [comment]
> > Hey @riccardoperra I have updated , please have a look
> 
> There are no changes in the pr

Looks like the changes did not get pushed, will push the changes and update you

**Comment by riccardoperra** [comment]
@SIMRAN88 Hey, I may need this theme ASAP for an internal use.

After the Monokai Pro is ready, is it a problem if you may switch to another issue like https://github.com/riccardoperra/codeimage/issues/369 or https://github.com/riccardoperra/codeimage/issues/368 instead of this? 

This issue also requires to have Fleet installed in the pc and interpret their configuration file since there are no example available yet
