### ISSUE TITLE
🚀 - Support maintaining maximum tab size

### ISSUE THREAD

**Issue by EndBug** [riccardoperra/codeimage#384]
### Which @codeimage/* package(s) are relevant/releated to the feature request?

Don't known / other

### Description

Hi, awesome tool!
It would be cool if there was a way to keep the same tab size when switching tabs, so that you could add a "switch effect" to the slides as if you clicked the other tab in an editor.
Let me know if that makes any sense 😅

**Comment by riccardoperra** [comment]
Hey, thank you 😄 Unfortunately I didn't understand the request pretty well, could you be more specific?

At the moment tabs keeps their own size based of the text content for both Accent/Non-accent modality

**Comment by EndBug** [comment]
Nevermind, I found out that if you manually set the image width and then manually add the missing lines you can get the effect I was (poorly) trying to explain 😅 
Sorry for the trouble ahahhah
