### ISSUE TITLE
🚀 - Add a way to disable syntax highlighting

### ISSUE THREAD

**Issue by EndBug** [riccardoperra/codeimage#385]
### Which @codeimage/* package(s) are relevant/releated to the feature request?

Don't known / other

### Description

As of now, there's no way to disable syntax highlighting completely: if you find yourself with a language and/or a type of file that is not supported by the website, you'll still have to choose one.

The only workaround is to remove CSS properties with the browser's webtools.

**Comment by riccardoperra** [comment]
Hey @EndBug , what do you think a out a “Plain Text” selectable option? 

I also can make a binding for .txt estension with a custom icom

**Comment by EndBug** [comment]
That would be great ;)

**Comment by riccardoperra** [comment]
Perfect 😄 I will mark this feature as a Medium priority and but this will be deployed with the release of 1.0 version

**Comment by riccardoperra** [comment]
Hey @EndBug, I've just opened a PR to add the new "language". 

![image](https://user-images.githubusercontent.com/37072694/197403360-ef02fdfd-8ea7-481a-b169-c35e747fee78.png)

What do you think? Do you have any suggestions? If all is ok I'm going to merge it

**Comment by EndBug** [comment]
Awesome! I've left a review ❤️

**Comment by riccardoperra** [comment]
Hey @EndBug, since [1.0 release](https://github.com/riccardoperra/codeimage/releases/tag/v1.0.0) has been deployed, also the new extension is now present in the editor 😄

**Comment by EndBug** [comment]
Awesome! 👏🏻
