### ISSUE TITLE
🚀 - Export to clipboard

### ISSUE THREAD

**Issue by micnic** [riccardoperra/codeimage#387]
### Which @codeimage/* package(s) are relevant/releated to the feature request?

codeimage

### Description

It would be great to have the possibility to save the generated image to clipboard on export. When preparing some code screenshots I do multiple tries and have to spam my file system, but with export to clipboard would keep it clean and I'll be able to paste in the presentation faster and easier. I would even recommend to make this the default behavior of CodeImage.

**Comment by riccardoperra** [comment]
Hey @micnic, I think you already could do that by pressing <kbd>Ctrl+C</kbd> I think (it's just a shortcut available when the editor code is not focused, clicking outside of the canvas or by clicking <kbd>Esc</kbd>).

Anyway I am planning to make these actions more available using a toolbar of actions (copy, formatting etc...) 😄

**Comment by micnic** [comment]
Oh, ok, did not know about all these stuff, thanks for the info. Feel free to close this issue if it is not actual.

**Comment by riccardoperra** [comment]
I'm updating the labels in order to not forgot this 😄 Probably I will work on the updates in a few weeks

**Comment by riccardoperra** [comment]
Just to inform you @micnic 😄, [1.0 release](https://github.com/riccardoperra/codeimage/releases/tag/v1.0.0) has been deployed so this issue will be moved in progress soon

**Comment by micnic** [comment]
Thank you for keeping me updated 😄

**Comment by riccardoperra** [comment]
Finally an update of this feature :smile:

![image](https://user-images.githubusercontent.com/37072694/208255510-816cef29-3c02-4623-9268-c7f9a9e5bb41.png)

The idea is to have a toolbar for the "canvas" in order to have extra actions e.g. Copy to clipboard, Format etc..

Any suggestion?

**Comment by micnic** [comment]
I think it looks great as it is, simple and accessible. Nice job!

**Comment by riccardoperra** [comment]
Shipped with [1.1.0](https://github.com/riccardoperra/codeimage/releases/tag/v1.1.0) release
