### ISSUE TITLE
🚀 - Support for Ruby syntax

### ISSUE THREAD

**Issue by djrobby** [riccardoperra/codeimage#393]
### Which @codeimage/* package(s) are relevant/releated to the feature request?

ui

### Description

As per my title. Can you please add support for Ruby syntax? Thank in advance!

**Comment by riccardoperra** [comment]
Hey @djrobby, yes 😄

It'something already built-in in the editor so I think it will be ready for tomorrow's deploy

**Comment by djrobby** [comment]
Thank you 🙏

**Comment by riccardoperra** [comment]
@djrobby ruby syntax is now available in [1.0.2](https://github.com/riccardoperra/codeimage/releases/tag/v1.0.2)
