### ISSUE TITLE
🚀 -  Let user use custom fonts or Fonts installed in the Machine/PC.

### ISSUE THREAD

**Issue by KunalTanwar** [riccardoperra/codeimage#423]
### Which @codeimage/* package(s) are relevant/releated to the feature request?

ui, Don't known / other

### Description

Now, we only have 6 fonts to choose from. But I want to use custom monospace font which is already installed in my PC. Please add a support for that too.

**Comment by riccardoperra** [comment]
Hi, I don’t think that this is possible since the browser is not able to retrieve the available system installed fonts

**Comment by KunalTanwar** [comment]
Well can we use a walkaround method like [Carbon](carbon.now.sh) did!! Uploading font file and then use it thoroughly.

**Comment by riccardoperra** [comment]
Didn’t thought about that 😄 then ok , I need to think a little for how to integrate this in both core and ui, since I was thinking to refactor also the font management  👌🏻

**Comment by riccardoperra** [comment]
Currently resuming this since I discover about https://developer.mozilla.org/en-US/docs/Web/API/Local_Font_Access_API

Don't know yet when it will be moved in progress 😄
