### ISSUE TITLE
🚀 - Vue Support

### ISSUE THREAD

**Issue by kupoback** [riccardoperra/codeimage#424]
### Which @codeimage/* package(s) are relevant/releated to the feature request?

Editor Language

### Description

Would love it if you could get Vue syntax support. You have the icon for it, but the Language Editor defaults to "Typescript", which isn't always the syntax case for Vue.

**Comment by riccardoperra** [comment]
This may take a while since CodeMirror 6 doesn't have vue language as is core, but there is already an integration for cm5

I need to do some investigation in order to understand what's needed to mix languages and add some vue rules to the current parser 😄

**Comment by riccardoperra** [comment]
Hey @kupoback, i'm not a vue user ..is this highlight ok? I tried to add both tsx and html language while using .vue extension 

![image](https://user-images.githubusercontent.com/37072694/208253739-32406b27-2888-497c-9056-f7f10995c2b2.png)

**Comment by kupoback** [comment]
> Hey @kupoback, i'm not a vue user ..is this highlight ok? I tried to add both tsx and html language while using .vue extension
> 
> ![image](https://user-images.githubusercontent.com/37072694/208253739-32406b27-2888-497c-9056-f7f10995c2b2.png)

Yeah, this looks great! I was going to suggest taking a look at the Examples documentation on Vue to see what could be combined, but using HTML/CSS and TypeScript should be just fine!

https://vuejs.org/examples/#fetching-data

**Comment by riccardoperra** [comment]
Perfect, it seems the same I think 😄 
![image](https://user-images.githubusercontent.com/37072694/208254044-2b58da25-105b-490b-a6cc-e2874bbad81d.png)

I've opened a pr #429 with that demo https://codeimage-app-pr-429.vercel.app/

This will be deployed tomorrow I think

**Comment by kupoback** [comment]
Looks good to me! Great work!

**Comment by riccardoperra** [comment]
@kupoback Deployed now with [1.0.9](https://github.com/riccardoperra/codeimage/releases/tag/v1.0.9) release
