### ISSUE TITLE
🐞 - Changing Programming language doesn't change file extension

### ISSUE THREAD

**Issue by hadiyarajesh** [riccardoperra/codeimage#442]
### Which @codeimage/* package(s) are the source of the bug?

codeimage, ui

### Description

When selecting a new language, it does not change file extension in UI. 
Let's suppose `TypeScript` is selected by default, so there will be a `TypeScript` icon and `index.tsx` filename.
Now, If I change the language to `Kotlin`, the logo will be correctly updated, but filename will remain `index.tsx` which is incorrect. It should be changed to `index.kt` 

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by riccardoperra** [comment]
Hey @hadiyarajesh, thanks for reporting the issue 😄 I'll roll out the fix tomorrow

**Comment by riccardoperra** [comment]
Up with [v1.1.1](https://github.com/riccardoperra/codeimage/releases/tag/v1.1.1) release 😄

**Comment by hadiyarajesh** [comment]
Perfect. Thanks @riccardoperra
