### ISSUE TITLE
🐞 - An error occurred while saving (Firefox)

### ISSUE THREAD

**Issue by ijkml** [riccardoperra/codeimage#445]
### Which @codeimage/* package(s) are the source of the bug?

ui

### Please provide a screenshot or a video to a minimal reproduction of the bug

[Screencast 2023-01-13 16:34:27.webm](https://user-images.githubusercontent.com/52390439/212361011-7ab28658-ac84-415a-a9da-44a2e19a5615.webm)

### Description

Exporting or trying to open (link) in Firefox results throws an error, "An error occurred while saving". Does not matter if I'm logged in or not. No error in console either. Also tried latest Firefox Developer Edition, doen't work either. But it works fine in Chromium.

Firefox version: 108.0.1
OS: Linux Mint 21.1

### Which browsers have you used?

- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux
- [ ] iOS
- [ ] Android

**Comment by riccardoperra** [comment]
Hi, the video is not working :(

Is something logged on the console?

**Comment by ijkml** [comment]
https://user-images.githubusercontent.com/52390439/212388601-7bc1b1d2-2616-47ca-b2c8-04ef9d39b5b4.webm

Here's the video again. I hope this one works. 

And, no. No error on the console. Just html warnings "...was preloaded using link preload but not used within a few seconds..."
Checked the network tab, no errors.

**Comment by riccardoperra** [comment]
Ok perfect, I've managed to reproduce the issue on my firefox too 😄 That could be a regression caused by this issue #432

I will check on it this weekend and deploy a fix asap 😄 

Thanks for reporting the issue

**Comment by riccardoperra** [comment]
Resolved with [v1.1.2 release](https://github.com/riccardoperra/codeimage/releases/tag/v1.1.2) 😄 Seems that firefox wasn't able to fetch values from css files at runtime like chrome does 

Thanks for reporting the issue!

**Comment by ijkml** [comment]
That was fast! 🚀 
Many thanks!
