### ISSUE TITLE
🚀 - Add settings for defaults

### ISSUE THREAD

**Issue by Desoroxxx** [riccardoperra/codeimage#451]
### Which @codeimage/* package(s) are relevant/releated to the feature request?

Don't known / other

### Description

In the settings page it would be awesome if a defaults sections was added where you can set you default theme and parameters

**Comment by riccardoperra** [comment]
I can take it in consideration, but there are some things that I need to take care about.

My idea is to add a “Save preset” button in the editor panel, which will store the configuration remotely for logged in users.

Next, you will have access to a “My Preset” page which will collects all the saved presets, with a preview of the configured theme.

This can be integrated maybe also in a future with the #399 

What do you think about this?

**Comment by JustDesoroxxx** [comment]
I think this would be perfect!

**Comment by riccardoperra** [comment]
We merged today on the main branch all updates for the presets feature, it will be deployed soon after some testing and some improvements 😄

**Comment by riccardoperra** [comment]
To be deployed in 1.4.0

**Comment by riccardoperra** [comment]
We are not saving language in presets because you can have multiple tabs with different languages. Currently presets are just saving the “style” properties
