### ISSUE TITLE
🚀 - Auto Day/Night Mode

### ISSUE THREAD

**Issue by JustDesoroxxx** [riccardoperra/codeimage#460]
### Which @codeimage/* package(s) are relevant/releated to the feature request?

Don't known / other

### Description

Currently I only have choices for dark/night and light/day themes for codeimage, but my current setup automatically follows day and night by switching theme when the sun goes up and down so it is very annoying to always switch between the two.

So could an option for codeimage to follow system theme be added?

**Comment by riccardoperra** [comment]
Available with [1.1.6](https://github.com/riccardoperra/codeimage/releases/tag/v1.1.6) release 😄
