### ISSUE TITLE
Can you add c# to the supported languages? 🚀 - 

### ISSUE THREAD

**Issue by keparlak** [riccardoperra/codeimage#463]
### Description

We often create snippets in C# and want them to be rendered with correct coloring. We would be glad if you add this feature for us.

**Comment by riccardoperra** [comment]
Hey @keparlak, thanks to @hackpirodev we added support for c# 😄 since we are using CodeMirror6 and legacy mode , probably highlighting doesn’t cover keywords for c# newest version, but the most should be ok 

we will schedule a deploy tomorrow morning around 9.00 CET 😄 

thanks 🙏

**Comment by keparlak** [comment]
Thank you.
