### ISSUE TITLE
🚀 - Support screenshots

### ISSUE THREAD

**Issue by truongduyng** [riccardoperra/codeimage#467]
### Which @codeimage/* package(s) are relevant/releated to the feature request?

Don't known / other

### Description

Besides code/text, it would be nicer if you support screenshots too

**Comment by riccardoperra** [comment]
Hi, @truongduyng, after a discussion with @hackpirodev we believe that the effort required for this feature is not so much, but it doesn't reflect much the codeimage idea at the moment.

For now we are focusing on improving the code editor and we have several activities planned, so we cannot work on what you requested in the short term

**Comment by truongduyng** [comment]
Hi @riccardoperra, thank you for your response. Im really impressed by your work. I knew that this request didn't reflect the codeimage. Your app name itself is self-explained what it does. Just that I see many other screenshot apps do the same thing with codeimage but although its quality is worse than codeimage they have a bigger number of users.

Would be worth it if you clone another version for screenshot?
