### ISSUE TITLE
🚀 - Sort languages

### ISSUE THREAD

**Issue by goncy** [riccardoperra/codeimage#469]
### Which @codeimage/* package(s) are relevant/releated to the feature request?

config

### Description

![image](https://user-images.githubusercontent.com/6494462/221361671-914cb27d-6872-4117-bb17-13916a36aa6f.png)

I guess its intentional to leave Typescript and Javascript first, but the rest of the languages are not sorted.

Possible solutions:
* Sort `SUPPORTED_LANGUAGES` by label.
* Add a `featured` property to `LanguageDefinition` and when sorting `SUPPORTED_LANGUAGES` leave featured languages on top

Haven't created a PR because I think its a pretty personal opinion.

**Comment by riccardoperra** [comment]
Hey @goncy, I like the idea to add the featured property!

Then languages can be sorted here in order to put in the top the featured ones 

https://github.com/riccardoperra/codeimage/blob/0795ddaf34536ddef04f1ab7d0101a0ddd826543/apps/codeimage/src/components/PropertyEditor/EditorStyleForm.tsx#L17

**Comment by goncy** [comment]
I'm not being able to run the project on my local or code sandbox, but my idea is to turn this:

```tsx
export const EditorStyleForm: ParentComponent = () => {
  const languages = SUPPORTED_LANGUAGES;
  const fonts = SUPPORTED_FONTS;
```

Into this"
```tsx
const languages = SUPPORTED_LANGUAGES.sort((a, b) => a.featured || b.featured ? 1 : a.label.localeCompare(b.label));
const fonts = SUPPORTED_FONTS;

export const EditorStyleForm: ParentComponent = () => {
```

As those variables never change, there is no need to leave them on the render, and we can sort them just once.

This feature assumes a `featured` property is added to the `LanguageDefinition` type.

The same thing can be applied to fonts if needed. Not sure if this sorting should be made to any other place of the application. To think if it makes sense to move the sorting to the original constants file.

**Comment by riccardoperra** [comment]
I noticed now that with latest codesandbox vm restrictions there are some memory issues during the sandbox initialization :/ 

I'll try to fix and in case update the guide if needed. Instead, which issues did you had running your environment in your local environment? 

I'm also ok with the suggested changes. Sorting should also be ok only in that place, there aren't others place where these variables are used as I remember
