### ISSUE TITLE
🐞 - App loads just on incognito

### ISSUE THREAD

**Issue by goncy** [riccardoperra/codeimage#471]
### Which @codeimage/* package(s) are the source of the bug?

codeimage

### Please provide a screenshot or a video to a minimal reproduction of the bug

https://app.codeimage.dev/

### Description

![image](https://user-images.githubusercontent.com/6494462/221362406-9f35c0bc-c3c9-47cd-bf48-72efb889b041.png)

App doesn't load but loads on incognito, using Brave on Windows.

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by riccardoperra** [comment]
Hi, i'm not able to reproduce this issue using Brave on windows 🤔 Do you have some extension installed that may cause conflicts? I did the test with the latest brave version (v1.48.171)

**Comment by goncy** [comment]
Yes, it was my first guess so I disabled plenty of them but I still get the problem. Will debug disabling some more.

**Comment by goncy** [comment]
Effectively, it was caused by `Apollo Client Devtools` for some reason. Disabling it makes the app load correctly

**Comment by riccardoperra** [comment]
Thanks 🙏

Anyway I will try to debug this using the extension you mentioned and fix the issue 😃
