### ISSUE TITLE
🐞 - Some configurations doesn't persist after refresh

### ISSUE THREAD

**Issue by goncy** [riccardoperra/codeimage#473]
### Which @codeimage/* package(s) are the source of the bug?

codeimage

### Description

Before refresh:
![image](https://user-images.githubusercontent.com/6494462/221417473-b6eda35d-d000-40cb-ac9d-f9729bb9ed1d.png)

After refresh:
![image](https://user-images.githubusercontent.com/6494462/221417494-f552f351-f206-4d04-afb7-e879c5db00cc.png)

Line number and theme are the ones not being preserved.

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by riccardoperra** [comment]
Thanks for noticing that issue 😄 It has been fixed with #474 and it will be online in a short time
