### ISSUE TITLE
🚀 - Option to disable ligatures in fonts

### ISSUE THREAD

**Issue by Brian-Pob** [riccardoperra/codeimage#483]
### Which @codeimage/* package(s) are relevant/releated to the feature request?

codeimage

### Description

Some people, like myself, prefer seeing code without ligatures that combine certain character combinations like `>>` or `=>`. I think an option to enable/ disable this would be a good addition to CodeImage.

**Comment by riccardoperra** [comment]
Hi, this is a good idea 🙂 I will add this option soon (probably even during the day)

**Comment by riccardoperra** [comment]
Ready with #486  pr 😄 Will be deployed very soon

**Comment by riccardoperra** [comment]
Available with [1.3.0](https://github.com/riccardoperra/codeimage/releases/tag/v1.3.0) 😄
