### ISSUE TITLE
🚀 - Plugins

### ISSUE THREAD

**Issue by Desoroxxx** [riccardoperra/codeimage#495]
### Which @codeimage/* package(s) are relevant/releated to the feature request?

Don't known / other

### Description

It would be nice if by just selecting the code in our preferred IDE and right clicking there would be an option to directly open in CodeImage, this would go perfectly with #451 and #472.

**Comment by riccardoperra** [comment]
This feature probably requires also #490 

We’ll look into it next days / week after we complete the preset feature, currently development is a bit slowed down since I’m on vacation and my friend is sick
