### ISSUE TITLE
More Language Support🚀 - 

### ISSUE THREAD

**Issue by SH-Codes** [riccardoperra/codeimage#541]
### Description

Dart language support

**Comment by riccardoperra** [comment]
Hi, would you mind opening a PR? There should be a few changes to do 

https://github.com/riccardoperra/codeimage/pull/464

The dart language is still in the codemirror/legacy-modes/clike package

**Comment by riccardoperra** [comment]
Deployed in [1.4.1](https://github.com/riccardoperra/codeimage/releases/tag/v1.4.1)
