### ISSUE TITLE
🐞 - JSON is not formatted correctly

### ISSUE THREAD

**Issue by ony3000** [riccardoperra/codeimage#546]
### Which @codeimage/* package(s) are the source of the bug?

Don't known / other

### Description

According to the [release notes](https://github.com/riccardoperra/codeimage/releases/tag/v1.1.0), codeimage seems to use prettier as a formatting tool.
However, JSON requires double quotes to be used around property names.

Here are two screenshots for comparison.

![codeimage](https://github.com/riccardoperra/codeimage/assets/8164191/8c897ce2-0690-4b04-90a6-378ce1d8f739)

![prettier](https://github.com/riccardoperra/codeimage/assets/8164191/5ffd5121-aeae-4ac7-94b8-2a0ef0bdf9ac)

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Edge

### Which operating systems have you used?

- [X] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by riccardoperra** [comment]
Hey, currently there is the json5 parser which is supporting the object keys without double quotes 

https://github.com/riccardoperra/codeimage/blob/a166585035b05348713fdcde9dcb72e095c28bdd/packages/config/src/lib/base/languages.ts#L509

**Comment by ony3000** [comment]
Hmm, did you intentionally use the json5 parser instead of the json parser?

**Comment by riccardoperra** [comment]
It was mainly used to support formatting when using comment inside the json code…so yes 😕

**Comment by ony3000** [comment]
All right, I see. If so, are there any plans to support json parser and json5 parser as separate languages in the future?

**Comment by riccardoperra** [comment]
@ony3000 I think the best solution could be allows multiple formattings like VSCode does, and add a select to choose the formatter to use. What do you think? It could be a new select input field that appears under the `language` select if the language has multiple formatter

**Comment by ony3000** [comment]
That seems like a good solution.

**Comment by ony3000** [comment]
@riccardoperra It looks good to me. Thank you for your effort.

**Comment by riccardoperra** [comment]
Released with [1.4.2](https://github.com/riccardoperra/codeimage/releases/tag/v1.4.2)
