### ISSUE TITLE
🚀 - Export with rounded corners

### ISSUE THREAD

**Issue by Desoroxxx** [riccardoperra/codeimage#547]
### Which @codeimage/* package(s) are relevant/releated to the feature request?

codeimage

### Description

When displaying on the code image website the corners are rounded which is nice, but the actual exported png does not have rounded corners.

It would be very nice to have an option for exporting with rounded corners.

**Comment by riccardoperra** [comment]
Hi, do you have an use case for that?

**Comment by Desoroxxx** [comment]
> Hi, do you have an use case for that?

Yeah actually, GitHub does not round images and in [my changelogs](https://github.com/Red-Studio-Ragnarok/Red-Core/blob/main/Changelog.md) I feel like the square corners looks a bit harsh compared to the rounded window

**Comment by riccardoperra** [comment]
Working on this, there will be a new option to select the current radius of the frame

![image](https://github.com/riccardoperra/codeimage/assets/37072694/b009db1e-dd01-4403-b112-e2cf65222be1)

New snippets will always be exported with the default radius (8px), to remove the border you will have to put the radius to "8". What do you think?

**Comment by Desoroxxx** [comment]
> Working on this, there will be a new option to select the current radius of the frame
> 
> ![image](https://user-images.githubusercontent.com/37072694/262050923-b009db1e-dd01-4403-b112-e2cf65222be1.png)
> 
> New snippets will always be exported with the default radius (8px), to remove the border you will have to put the radius to "0". What do you think?

I think that's great, does it visually show in the editor?

**Comment by riccardoperra** [comment]
> > Working on this, there will be a new option to select the current radius of the frame
> > ![image](https://user-images.githubusercontent.com/37072694/262050923-b009db1e-dd01-4403-b112-e2cf65222be1.png)
> > New snippets will always be exported with the default radius (8px), to remove the border you will have to put the radius to "0". What do you think?
> 
> I think that's great, does it visually show in the editor?

Yes

**Comment by riccardoperra** [comment]
@Desoroxxx https://codeimage-app-pr-553.vercel.app/ a public preview is available here..if everything is ok I will deploy it in the next few days

**Comment by Desoroxxx** [comment]
Just tested seems to work perfectly

**Comment by riccardoperra** [comment]
Released with [1.4.2](https://github.com/riccardoperra/codeimage/releases/tag/v1.4.2)
