### ISSUE TITLE
Python string color highlighting can glitch out

### ISSUE THREAD

**Issue by rsftb** [riccardoperra/codeimage#567]
### Which @codeimage/* package(s) are the source of the bug?

Don't known / other

### Please provide a screenshot or a video to a minimal reproduction of the bug

![IMG_3894](https://github.com/riccardoperra/codeimage/assets/132225296/efcf65a8-c599-4247-94dd-91cca97d515e)

### Description

Sometimes the colored strings starts coloring text outside of the string. Provided a screenshot of the issue

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [X] iOS
- [ ] Android

**Comment by rsftb** [comment]
![IMG_3894](https://github.com/riccardoperra/codeimage/assets/132225296/7c44202f-b167-4471-82c5-2ab9456d9d2a)

**Comment by riccardoperra** [comment]
Unfortunately I haven't any knowledge of python and the highlighting is handled by CodeMirror :( 

Sometimes this is caused due to some special cases or new language highlighting features that aren't already supported by the library I use
