### ISSUE TITLE
🐞 - Executing pnpm install fails

### ISSUE THREAD

**Issue by declanchiu** [riccardoperra/codeimage#568]
### Which @codeimage/* package(s) are the source of the bug?

codeimage

### Please provide a screenshot or a video to a minimal reproduction of the bug

*

### Description

![image](https://github.com/riccardoperra/codeimage/assets/55419399/878f2476-6b05-4460-ac09-b3796b3d9fc8)

node: 18.16.0 节点：18.16.0

pnpm: 8.7.6 下午：8.7.6

masos: Sonoma 14.0 马索斯：索诺玛 14.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by riccardoperra** [comment]
Hi, I’m not able to reproduce that issue and it seems that the error is related to a a connection issue.. the file pnpm tries to resolve exist in GitHub https://github.com/railwayapp/cli/releases/tag/v3.3.1
