### ISSUE TITLE
🚀 - Red Underline Text Formatting

### ISSUE THREAD

**Issue by Chucks1093** [riccardoperra/codeimage#569]
### Description

I would like to propose a feature enhancement to enable users to apply a red underline formatting to text, similar to the way TypeScript displays errors in many code editors. This formatting would be useful for emphasizing critical information or indicating errors within text.

![image](https://github.com/riccardoperra/codeimage/assets/90640297/a23f4bf7-8a1f-4dac-966c-cf6cbb7c1959)

**Comment by riccardoperra** [comment]
sorry if I'm only replying now. The idea is interesting, but I need to explore a bit to see how to integrate something like this. I'll probably start doing something in December
