### ISSUE TITLE
🚀 - Support for pasting rich text from VSCode

### ISSUE THREAD

**Issue by Not-Jayden** [riccardoperra/codeimage#577]
### Description

There are a lot of languages out there without proper support for syntax highlighting, seemingly primarily due to the bottleneck of what languages codemirror can support. Particularly, I was trying to use CodeImage to display some Svelte code, but unfortunately could not get the syntax highlighting I was hoping for.

As a workaround, I suspect adding support for pasting RTF data (like you get when copying from VSCode) would be a simple(r) and more flexible approach for support syntax highlighting for any language.

**Comment by riccardoperra** [comment]
What do you mean pasting RTF data? Just like google docs?

![image](https://github.com/riccardoperra/codeimage/assets/37072694/e7d7e912-7a7c-4136-9ada-6de6aa5f76f7)

**Comment by Not-Jayden** [comment]
@riccardoperra Yep exactly. I didn't properly investigate how the copied data from VSCode, looking at it more it seems like it's just HTML.

e.g. copying this from vscode
<img width="448" alt="image" src="https://github.com/riccardoperra/codeimage/assets/16816250/d1e794d6-fbd3-4784-8c12-4498b12763ea">

gives me this raw data in my clipboard
```html
<meta charset='utf-8'><div style="color: #cccccc;background-color: #1f1f1f;font-family: Fira Code, Menlo, Monaco, 'Courier New', monospace, Menlo, Monaco, 'Courier New', monospace;font-weight: normal;font-size: 12px;line-height: 18px;white-space: pre;"><div><span style="color: #569cd6;">const</span><span style="color: #cccccc;"> </span><span style="color: #4fc1ff;">colourStatusPositive</span><span style="color: #cccccc;"> </span><span style="color: #d4d4d4;">=</span><span style="color: #cccccc;"> </span><span style="color: #ce9178;">'#00d592'</span><span style="color: #cccccc;"> </span><span style="color: #c586c0;">satisfies</span><span style="color: #cccccc;"> </span><span style="color: #4ec9b0;">ColourHex</span><span style="color: #cccccc;">;</span></div></div>
```

Good to know about Svelte, I can maybe give that a go later. Though in fairness I think there are a lot of more popular languages that deserve to be added beforehand, which is why I figure supporting rich text/html potentially might be higher value for more people.

**Comment by riccardoperra** [comment]
That would be helpful but very difficult to handle in my opinion 😫 I need to do a bit of investigation 

How do I know if the user want to paste rtf or just the code? 

Currently the editable zone is entirely made with CodeMirror, in that case I should add a new “modality” and probably let the editor readonly.

Another case, what if I want to edit the pasted text? I should probably return to my editor, then change the code, then paste again to CodeImage.

If you have any ideas, I gladly accept feedback 😃
