### ISSUE TITLE
🚀 - Support for C Programming Language

### ISSUE THREAD

**Issue by KunalTanwar** [riccardoperra/codeimage#593]
### Description

It will be great to have C Programming Support because recently I have been in a situation where I need to make the code snapshot but didn't find any tool. So I used figma and edit every word to different colors copying from VS Code Color theme. It was so exhausting to do for every new code. Yeah that's all

**Comment by riccardoperra** [comment]
thats ok, it will be added in next update 😃 currently there is only the cpp language mode

**Comment by riccardoperra** [comment]
Available with [1.5.0](https://github.com/riccardoperra/codeimage/releases/tag/v1.5.0)
