### ISSUE TITLE
🐞 - Tab Title Font is different when exporting

### ISSUE THREAD

**Issue by KunalTanwar** [riccardoperra/codeimage#594]
### Which @codeimage/* package(s) are the source of the bug?

codeimage

### Description

Currently you use Inter as UI font for the app! It also applies on Tab Bar but when exporting the image or opening it in a new tab the font changes to the default OS font! which kinda look ugly especially on windows (Segoe UI). So, did you leave it as it is intentionally?? If yes, then change it to Inter cause Segoe UI spoils the mood.

![image](https://github.com/riccardoperra/codeimage/assets/77537933/28b073cf-9738-44d3-9f67-2fbb68647713)

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [x] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by riccardoperra** [comment]
Hi, thanks for reaching me 😀 No, this was not intentional then it will be fixed for the next update

**Comment by riccardoperra** [comment]
Available with [1.5.0](https://github.com/riccardoperra/codeimage/releases/tag/v1.5.0)
