### ISSUE TITLE
🚀 - Language search input box

### ISSUE THREAD

**Issue by alexandercerutti** [riccardoperra/codeimage#614]
### Which @codeimage/* package(s) are relevant/releated to the feature request?

Don't known / other

### Description

<img width="276" alt="immagine" src="https://github.com/riccardoperra/codeimage/assets/5442545/4d313d88-a3b1-419a-93af-6d4285f7029f">

This is the current situation. The support list might get longer and longer. Introducing a search bar in the menu or the possibility to write and filter for the languages in the input itself would be a great thing.

Thank you!

**Comment by riccardoperra** [comment]
> [!NOTE]
> - must add combobox input to https://github.com/riccardoperra/codeui
> - https://kobalte.dev/docs/core/components/combobox
> - Minimal implementation for tab name: https://github.com/riccardoperra/codeimage/blob/main/apps/codeimage/src/components/Terminal/Tabs/TabName/TabName.tsx
