### ISSUE TITLE
🚀 - Customize line numbers starting number

### ISSUE THREAD

**Issue by alexandercerutti** [riccardoperra/codeimage#615]
### Which @codeimage/* package(s) are relevant/releated to the feature request?

Don't known / other

### Description

It would be nice to let line numbers to start from a specific arbitrary positive number.

Thank you!

**Comment by riccardoperra** [comment]
initial implementation: https://github.com/riccardoperra/codeimage/pull/613

**Comment by riccardoperra** [comment]
Implementation ready in this pr https://github.com/riccardoperra/codeimage/pull/624.
Will be deployed in next update

**Comment by riccardoperra** [comment]
Finally had the time to merge it 😄 Will be available soon in prod

**Comment by riccardoperra** [comment]
Released with [1.6.0](https://github.com/riccardoperra/codeimage/releases/tag/v1.6.0). Thanks 😄

**Comment by riccardoperra** [comment]
P.S. Alla fine ti ho nominato anche nel changelog dentro l'app 😬 Prima o poi rilascero anche il resto
