### ISSUE TITLE
🚀 - YAML Language Support

### ISSUE THREAD

**Issue by nhedger** [riccardoperra/codeimage#618]
### Which @codeimage/* package(s) are relevant/releated to the feature request?

codeimage, highlight

### Description

Hey,

Thanks for building this awesome tool.

I was wondering whether YAML language highlighting could be added to the code editor.

Cheers

**Comment by riccardoperra** [comment]
Yes, it will be added in the next update

**Comment by nhedger** [comment]
Much appreciated, thanks!

**Comment by riccardoperra** [comment]
Available with latest 1.5.1 update 😄 
https://github.com/riccardoperra/codeimage/releases

**Comment by nhedger** [comment]
Thank you so much!
