### ISSUE TITLE
🚀 - Allow padding to be Zero

### ISSUE THREAD

**Issue by SarjuHansaliya** [riccardoperra/codeimage#623]
### Which @codeimage/* package(s) are relevant/releated to the feature request?

ui

### Description

Currently padding options are `16`, `32`, `64`, `128`.

It would be great if it allow `0` option also.

If you think this is helpful, I can work on creating PR.

**Comment by riccardoperra** [comment]
Hi, yes this could be helpful 🙂

In my opinion the segmentedControl cannot be used anymore there is no enough space for five items. Instead, we should use the <Select/> control.

Anyway, some info for the pr:

Here’s the configuration file with the padding settings
[configuration.ts](https://github.com/riccardoperra/codeimage/blob/main/apps/codeimage/src/core/configuration.ts)

I’d recommend you to refactor the current number[] array to a key-value object with `label` and `value` property, just like the “editorRadius” config.

The editor ui for padding is here: [FrameStyleForm](https://github.com/riccardoperra/codeimage/blob/main/apps/codeimage/src/components/PropertyEditor/FrameStyleForm.tsx
)

You can copy a select implementation from this:
 
https://github.com/riccardoperra/codeimage/blob/d3bcdacda3cd707500463ff0e4e2e5587584cacb/apps/codeimage/src/components/PropertyEditor/EditorStyleForm.tsx#L47-56

https://github.com/riccardoperra/codeimage/blob/d3bcdacda3cd707500463ff0e4e2e5587584cacb/apps/codeimage/src/components/PropertyEditor/EditorStyleForm.tsx#L106-120

**Comment by riccardoperra** [comment]
Hi, yes this could be helpful 🙂

In my opinion the segmentedControl cannot be used anymore there is no enough space for five items. Instead, we should use the Select control.

Anyway, some info for the pr:

Here’s the configuration file with the padding settings
[configuration.ts](https://github.com/riccardoperra/codeimage/blob/main/apps/codeimage/src/core/configuration.ts)

I’d recommend you to refactor the current number[] array to a key-value object with `label` and `value` property, just like the “editorRadius” config.

The editor ui for padding is here: [FrameStyleForm](https://github.com/riccardoperra/codeimage/blob/main/apps/codeimage/src/components/PropertyEditor/FrameStyleForm.tsx
)

You can copy a select implementation from this:
 
 
https://github.com/riccardoperra/codeimage/blob/d3bcdacda3cd707500463ff0e4e2e5587584cacb/apps/codeimage/src/components/PropertyEditor/EditorStyleForm.tsx#L47-L56

https://github.com/riccardoperra/codeimage/blob/d3bcdacda3cd707500463ff0e4e2e5587584cacb/apps/codeimage/src/components/PropertyEditor/EditorStyleForm.tsx#L106-L120

Note: currently the radius between the frame and the editor could be different, then the editor frame border radius should be 0 if frame passing is 0.

I think you can update here the “styles.terminalVars.radius” css variable

https://github.com/riccardoperra/codeimage/blob/d3bcdacda3cd707500463ff0e4e2e5587584cacb/apps/codeimage/src/components/Terminal/TerminalHost.tsx#L54-L66

**Comment by SarjuHansaliya** [comment]
awesome @riccardoperra thank you for the information, let me work on it.

**Comment by riccardoperra** [comment]
Thanks for your collaboration 😃 use the contributions.md to startup the project but if you need something, just ask.

if you don’t want to run docker etc because you don’t need the backend for this change, I think you will have to run the build command manually for each package in “packages” folder, except “api-types” (which requires you to have a backend with Postgres up)

**Comment by SarjuHansaliya** [comment]
@riccardoperra I have created PR here https://github.com/riccardoperra/codeimage/pull/625

**Comment by riccardoperra** [comment]
#625 to be merged

**Comment by riccardoperra** [comment]
Released with [1.6.0](https://github.com/riccardoperra/codeimage/releases/tag/v1.6.0). Thanks for your contribution :)

**Comment by SarjuHansaliya** [comment]
Awesome @riccardoperra Thanks for publishing those changes
