### ISSUE TITLE
🐞 - [Golang] Incorrect import declaration by auto completion 

### ISSUE THREAD

**Issue by afifurrohman-id** [riccardoperra/codeimage#633]
### Which @codeimage/* package(s) are the source of the bug?

codeimage

### Description

According golang spec this seem this invalid.
https://go.dev/ref/spec#Import_declarations

https://github.com/riccardoperra/codeimage/assets/118882411/04619cea-ca5e-447f-853c-a991058f5d4f

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [X] Linux
- [ ] iOS
- [ ] Android

**Comment by riccardoperra** [comment]
Hi, I suggest you to open an issue to @codemirror/lang-go package https://github.com/codemirror/lang-go/blob/main/src/snippets.ts
