### ISSUE TITLE
🚀 - Sharable presets

### ISSUE THREAD

**Issue by MidnightRocket** [riccardoperra/codeimage#636]
### Which @codeimage/* package(s) are relevant/releated to the feature request?

codeimage, ui

### Description

It would be nice to have a share presets functionality. Preferably via a url. 
<br/>
I have used this for school projects, to make the code much more presentable.
It is however a bit difficult get a consistent look across all code snippets when working in a group, as all group members needs to have the same preset. 
<br/>
It would be very nice if presets could be shared via a link. Maybe could the preset settings be embedded into the link as parameters. This avoids server side storage, and could provide a means to easily import presets between different hosted instances. 
<br/>
Keep up the amazing work! This is the sleekest and overall best code image generator out there. 
<br/>
*Not sure if I have selected the most appropriate packages*

**Comment by riccardoperra** [comment]
Hi, thanks for reaching me 😄 This shouldn't be a problem to add this feature, I just don't have a lot of time time :/ 

Hope I can work on this the next days

**Comment by riccardoperra** [comment]
@MidnightRocket available with 1.7.0 update

**Comment by MidnightRocket** [comment]
Awesome🤩 That was quick😁
