### ISSUE TITLE
🐞 - Update Fleet theme

### ISSUE THREAD

**Issue by OljaKli** [riccardoperra/codeimage#641]
### Which @codeimage/* package(s) are the source of the bug?

ui

### Description

Hello,

We’ve noticed that the color theme for Fleet is outdated. Could you please update it following the instructions provided in the links below?

[Building Custom Theme Plugins](https://www.jetbrains.com/help/fleet/building-custom-theme-plugins.html)
[Modifying Theme Settings](https://www.jetbrains.com/help/fleet/modifying-theme-settings.html)
Please ensure that you are not using any of the old, edited themes as a reference. Kindly delete the old theme from the folder and create a new one using the latest version of Fleet.

Thank you.

**Comment by riccardoperra** [comment]
Thanks for reaching me :) I've released a new version with the updated theme (here the related pr !642)
