### ISSUE TITLE
🚀 - Support Protobuf `proto3` / `proto2`

### ISSUE THREAD

**Issue by afifurrohman-id** [riccardoperra/codeimage#644]
### Which @codeimage/* package(s) are relevant/releated to the feature request?

codeimage

### Description

At least protobuf version 3 (`proto3`) need to supported

**Comment by riccardoperra** [comment]
Hi, I need more detailed information about this. What “protobuf” is exactly? It seems something related to python language, which is supported

**Comment by afifurrohman-id** [comment]
> Hi, I need more detailed information about this. What “protobuf” is exactly? It seems something related to python language, which is supported

No it's grpc related.
It's data serialization: https://protobuf.dev/
Which like json but more lightweight, that's make grpc much faster than REST.

**Comment by riccardoperra** [comment]
Didn't know about something like that 😄 Anyway, i'm opening a PR to support it since fortunately it's already supported by codemirror. Can you confirm to me if protobuf files have ".proto" extension?

Here's a preview
![image](https://github.com/user-attachments/assets/44ee1167-0fe7-408d-8556-f8a1b9971832)

**Comment by afifurrohman-id** [comment]
> Didn't know about something like that 😄 Anyway, i'm opening a PR to support it since fortunately it's already supported by codemirror. Can you confirm to me if protobuf files have ".proto" extension?

Yes, the preview it's awesome btw 🎉

**Comment by riccardoperra** [comment]
Available with [1.7.2](https://github.com/riccardoperra/codeimage/releases/tag/v1.7.2) 😄 Thanks
