### ISSUE TITLE
🚀 - Add support for Pascal programming language

### ISSUE THREAD

**Issue by r4ai** [riccardoperra/codeimage#651]
### Which @codeimage/* package(s) are relevant/releated to the feature request?

codeimage

### Description

Thank you for developing such an excellent piece of software!

It would be helpful if Pascal could be added as a supported language.

FYI, it seems that CodeMirror supports the Pascal language (I’m not familiar with CodeMirror, so I apologize if this is off the mark): https://github.com/codemirror/legacy-modes?tab=readme-ov-file#modepascal

**Comment by riccardoperra** [comment]
Released with [1.8.1](https://github.com/riccardoperra/codeimage/releases/tag/v1.8.1) 😄
