### ISSUE TITLE
🐞 - PHP requires an opening tag for syntax highlighting to work

### ISSUE THREAD

**Issue by PHLAK** [riccardoperra/codeimage#656]
### Which @codeimage/* package(s) are the source of the bug?

codeimage

### Description

PHP requires an opening tag (i.e. `<?php`) for syntax highlighting to work. Without the tag the code will only be white.

![Screenshot From 2024-12-06 19-38-33](https://github.com/user-attachments/assets/8d8acb93-10c5-4fb6-80b5-438ae2b31f7e)

![Screenshot From 2024-12-06 19-38-45](https://github.com/user-attachments/assets/23b3d09d-fced-46ee-adbd-c2f722002bcf)

### Which browsers have you used?

- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux
- [ ] iOS
- [ ] Android

**Comment by riccardoperra** [comment]
Released in https://github.com/riccardoperra/codeimage/releases/tag/v1.8.2 😄

**Comment by PHLAK** [comment]
Awesome, thank you!

**Comment by PHLAK** [comment]
@riccardoperra Highlighting without the opening tag is working as expected, however, now when the opening tag _is_ included the tag is now highlighted in two different colors and I don't think this was intentional.

<p align="center">
  <img src="https://github.com/user-attachments/assets/b366f34f-4519-4f0f-8c97-658b69a277a1" width="66%">
</p>

**Comment by riccardoperra** [comment]
I don’t think this can be fixed, it seems that with this mode “php” is recognized as a keyword. This Depends on the theme
