### ISSUE TITLE
🚀 - Swap the CSS icon to use the new official one

### ISSUE THREAD

**Issue by argyleink** [riccardoperra/codeimage#659]
### Which @codeimage/* package(s) are relevant/releated to the feature request?

Don't known / other

### Description

The new icon svg can be found here https://github.com/CSS-Next/logo.css

**Comment by riccardoperra** [comment]
Released with [1.8.3](https://github.com/riccardoperra/codeimage/releases/tag/v1.8.3)

![image](https://github.com/user-attachments/assets/5ba8a306-1a9e-4961-a08b-3eddc480f497)

Thanks 😄
